[package]
name = "launcher-java-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json", "blocking", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
zip = "5.1.1"
walkdir = "2.5.0"